class ValidationError(Exception):
    pass


class UserCreateError(Exception):
    pass
